### ISSUE TITLE
oobash

### ISSUE THREAD

**Issue by webfalter** [domachine/oobash#1]
Hallo,
ich bekomme Deine Beispiele https://forum.ubuntuusers.de/topic/objektorientierte-bash-skripte/ mit Person mit deiner Class hier nicht zum laufen. Wollte es mal probieren, da der Ansatz Objekt Orientiert irgendwas hat. Vielleicht hast Du ja auch in der Zwischenzeit das ganze noch mehr ausgebaut.

LG

**Comment by domachine** [comment]
Hi,

das ganze ist alles schon sehr lange her. Bin mir gar nicht mehr ganz sicher, was ich da angestellt habe. War alles als Experiment gedacht und nicht für produktive Einsatzzwecke. Ich schau mal ob ich demnächst mal wieder Zeit finde um etwas zu basteln. ☺️
